---

- name: "Create /etc/default/{{ laserweb_src_service }}"
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ laserweb_src_service }}"
    mode: "0644"
    validate: sh -n %s
  notify:
    - Restart LaserWeb
