---

- name: "Create /etc/rc.conf.d/{{ laserweb_src_service }}"
  template:
    src: FreeBSD.rc.conf.j2
    dest: "/etc/rc.conf.d/{{ laserweb_src_service }}"
    mode: "0644"
    validate: sh -n %s
  notify:
    - Restart LaserWeb
