---
# tasks file for ansible-role-LaserWeb-src

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create laserweb_src_group
  group:
    name: "{{ laserweb_src_group }}"

- name: Create laserweb_src_user
  user:
    name: "{{ laserweb_src_user }}"
    home: "{{ laserweb_src_home }}"
    comment: "{{ laserweb_src_user }} user"
    create_home: yes
    group: "{{ laserweb_src_group }}"
    groups: "{{ laserweb_src_groups }}"
    append: yes
    state: present

- name: Create laserweb_src_home
  file:
    path: "{{ laserweb_src_home }}"
    mode: "0755"
    owner: "{{ laserweb_src_user }}"
    group: "{{ laserweb_src_group }}"
    state: directory

- name: Checkout laserweb_src_scm_url
  git:
    dest: "{{ laserweb_src_scm_dest }}"
    recursive: yes
    repo: "{{ laserweb_src_scm_url }}"
    version: "{{ laserweb_src_version }}"
  become: yes
  become_user: "{{ laserweb_src_user }}"
  notify:
    - Build LaserWeb

- name: Install node modules
  command: npm ci
  args:
    chdir: "{{ laserweb_src_scm_dest }}"
    creates: "{{ laserweb_src_scm_dest }}/node_modules"
  become: yes
  become_user: "{{ laserweb_src_user }}"

- name: "Include configure-{{ ansible_os_family }}.yml"
  include: "configure-{{ ansible_os_family }}.yml"

- name: Start laserweb_src_service
  service:
    name: "{{ laserweb_src_service }}"
    state: started
